name: beautywise_ai
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  google_sign_in: ^6.2.2
  firebase_storage: ^12.4.3
  file_picker: ^9.0.2
  image_picker: ^1.1.2
  flutter_dotenv: ^5.2.1
  image: ^4.1.3  # Used for image processing
  firebase_ml_model_downloader: 0.3.3+2
  shared_preferences: ^2.5.2
  camera: ^0.10.5
  google_ml_kit: 0.16.3
  tflite_flutter: ^0.10.0
  firebase_analytics: ^11.4.4
  google_mlkit_face_detection: ^0.9.0
  camera_web: ^0.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
